# Understanding Scalar, Vector, and Matrix Operations

## Creating a matrix

In [1]:
import numpy as np

myMatrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix)
print(myMatrix[0,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1


In [2]:
myMatrix = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(myMatrix)
print(myMatrix[0, 1, 1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4


In [3]:
myMatrix = np.ones([4,4], dtype=np.int32)
print(myMatrix)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
myMatrix = np.ones([4,4,4], dtype=np.bool)
print(myMatrix)

[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [5]:
myMatrix = np.mat([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Performing matrix multiplication

In [6]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[3,4,5],[5,6,7]])

print(a.dot(b))

[[22 28 34]
 [49 64 79]]


In [8]:
a = np.mat([[1,2,3],[4,5,6]])
b = np.mat([[1,2,3],[3,4,5],[5,6,7]])

print(a*b)

[[22 28 34]
 [49 64 79]]


## Executing advanced matrix operations

In [11]:
changeIt = np.array([1,2,3,4,5,6,7,8])

print(changeIt)

print(changeIt.reshape(2,4))

print(changeIt.reshape(2,2,2))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
changeIt = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(np.transpose(changeIt))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [13]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)

print(np.allclose(np.dot(a,b), np.identity(2)))

True


## Extending analysis to tensors

In [18]:
inputs = np.array([5, 10, 15])
weights = np.array([[.5,.2,-1], [.3,.4,.1], [-.2,.1,.3]])

result = np.dot(inputs, weights)
print(result)

[2.5 6.5 0.5]


## Using vectorization effectively

In [25]:
def doAdd(a, b):
    return a + b

vectAdd = np.vectorize(doAdd)

print(vectAdd([1, 2, 3, 4], [1, 2, 3, 4]))

[2 4 6 8]
